config/routes.rb
  Rails.application.routes.draw do

  get 'access/login'
  get 'access/attempt_login'
  post 'access/attempt_login'
  get 'access/logout'
  get 'people/signup' 
  get 'access/landing'
  get 'access/home'
  
    resources :chores do
      collection do
        get 'complete'
      end
    end
    resources :people do
      collection do
        get 'joinhouse'
      end
    end
    resources :households do
      collection do
        get 'join'
      end
    end
        
    root :to => redirect('/access/landing')
    
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/') 
    
  end

 

app/controllers/access_controller.rb
class AccessController < ApplicationController
#Log in and user authentiction  
  before_action :confirm_logged_in, :except => [:landing, :login, :attempt_login, :logout]
  
  #Logs user in if they exist
  def attempt_login
    if params[:username].present? && params[:password].present?
      found_user = Person.where(:username => params[:username]).first
      if found_user
        authorized_user = found_user.authenticate(params[:password])
      end
    end
    
    if authorized_user
      session[:user_id] = authorized_user.id
      session[:first_name] = authorized_user.first_name
      
      #if new user, join a household
      if authorized_user.household_id == nil
        redirect_to("/households")
      #if returning user, go to homepage
      else
        redirect_to("/chores")
        flash[:notice] = "You are now logged in, " + authorized_user.first_name
      end
      
    else
      #if user does not exist, redirect to login
      redirect_to("/access/login")
      flash[:notice] = "Invalid username/password combination."
    end
  end
  
  #Log out and sets token to nil
  def logout
    session[:user_id] = nil
    session[:username] = nil
    flash[:notice] = 'Logged out'
    redirect_to('/chores')
  end
end

app/helpers/access_helper.rb
module AccessHelper
end

app/views/access/_login_form.html.erb
<!-- Log in form. Client side validation present with required: true-->
<%= label_tag(:username, nil, class: 'accessInput custom-control') %>
<%= text_field_tag(:username, params[:username], class: 'accessInput custom-control', required: true) %>
<%= label_tag(:password, nil, class: 'accessInput custom-control') %>
<%= password_field_tag(:password, nil, class: 'accessInput custom-control', required: true) %>
            
        

app/views/access/landing.html.erb
<!--See menage first page: Menage title with log in and sign up buttons-->
<div class="container-fluid" id="part1">

<!-- Landing page when user opens the app. Prompted with only two options, to sign up or to log in
Used table format to make layout look clean-->

    <!--Ménage title --> 
    <div class = "row" >
        <div id="title">
            <h1 style="color: white; font-size: 100px;">ménage</h1>
        </div>
    </div>
   
   <!--Log in and Sign up buttons-->
    <div class="row">
        <div class="col-xs-2 col-xs-offset-4">
            <div id="button1"</div>
                <%= link_to "Sign up", '/people/signup', :class => " button btn btn-lg" %>
            </div>
        </div>
        <div class="col-xs-2">
            <div id="button2">
                <%= link_to "Log in", '/access/login', :class => " button btn btn-lg" %>
            </div>
        </div>
    </div>
    
    <!--Allows you to scroll to part 2-->
    <div class="row"  style="color:white; justify-content: center; margin-top: 10%;">
        <a href="#part2"><i class="glyphicon glyphicon-chevron-down"></i></a>
    </div>
</div>

<!--Part 2 of Landing: description of Ménage-->
<div id = "part2" class="container-fluid" style="margin-bottom:25%">
    
    <!--Icon to Scroll up to Part 1 of landing-->
    <div class="row" style="color:white; justify-content: center;">
        <a href="#part1"><i class="glyphicon glyphicon-chevron-up"></i></a>    
    </div>
    
    <!--Ménage Description titles-->
    <div class="row" style="color:white; margin-top:5%;">
        <div class="col-md-3 offset-md-5">
            <h1 style="font-size: 50px;">ménage</h1>
        </div>
    </div>
    
    
    <!--Definition of Ménage-->
    <div class="row" style="justify-content: center;">
        <h2 style="font-style: italic;"> noun | mé·nage | \ mā-ˈnäzh , mə- \</h2>
    </div>
    <div class="row" style="justify-content: center; color:white; margin-bottom:none;">
        <h4>:members of a household</h4>
    </div>
    <div class="row" style="justify-content: center; color:white;">
        <h4>:the members of a household</h4>
    </div>
    <div class="row" style="justify-content: center; color:white;">
        <h4>origin: French</h4>
    </div>
    </br>
    </br>
    
    <!--Goal of Ménage-->
    <div class="row" style="justify-content: center; color:white;">
        <p style="font-size:20px">[an online app helping you tackle your chores and tasks between housemates, equitably]</p>
    </div>
    <div class="row" style="justify-content: center; color:white;">
        <p style="font-size:15px">work together | organize your house | move on with your life</p>
    </div>
    
    
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"></script>
<script src="https://use.fontawesome.com/a276842440.js"></script>

<script>
//Allows smooth scrolling between part 1 and part 2 of landing page
//Source: https://codepen.io/wesleyvanwyk1979/pen/iAxwr?page=1&
$(document).ready(function(){
	$('a[href^="#"]').on('click',function (e) {
	    e.preventDefault();

	    var target = this.hash;
	    var $target = $(target);

	    $('html, body').stop().animate({
	        'scrollTop': $target.offset().top
	    }, 900, 'swing', function () {
	        window.location.hash = target;
	    });
	});
});

</script>

app/views/access/login.html.erb
<!-- Log in view. User is prompted for username and password upon log in-->

<!--Creates house animation surrounding the log in fields*/-->
<%= render 'layouts/houseSVG' %>

<div id="signupWrapper">
    <!--Log in box-->
    <div class="box">
        <!--Go back button-->
        <div class="col-md-5">
            <a href="/access/landing" style="color:white;"><span style="font-size: 30px; margin-top: 5%;" class="glyphicon glyphicon-circle-arrow-left"></span></a>
        </div>
        
        <!--Log in Form-->
        <h2 style="color:white; margin-top: 5%">Login</h2>
        <%= form_tag(access_attempt_login_path, :class => 'regForm', :method => :post) do |f| %>
            <%= render(:partial => 'login_form', :locals => {:f => f}) %>
            <!--Log in Button-->
                <%= button_tag(type: 'submit',value: "submit", class: "submitBtn btn btn-primary", style: "margin-left: 55%; margin-top: 5%") do %>
                    <span class="glyphicon glyphicon-ok"></span> <% end %>
        <% end %>
    </div>
</div>