config/routes.rb
  Rails.application.routes.draw do

  get 'access/login'
  get 'access/attempt_login'
  post 'access/attempt_login'
  get 'access/logout'
  get 'people/signup' 
  get 'access/landing'
  get 'access/home'
  
    resources :chores do
      collection do
        get 'complete'
      end
    end
    resources :people do
      collection do
        get 'joinhouse'
      end
    end
    resources :households do
      collection do
        get 'join'
      end
    end
        
    root :to => redirect('/access/landing')
    
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/') 
    
  end

 

app/models/chore.rb
class Chore < ActiveRecord::Base
    #chore model with validations of task and priority lengths
    belongs_to :household
    
    validates :task, :presence => true,
                    :length => { :within => 2..50 }
    validates :priority, :presence => true,
                    :length => { :within => 2..50 }

           
end

app/controllers/chores_controller.rb
class ChoresController < ApplicationController
    #controller for both tasks and chores, with status being nil for tasks
    before_action :confirm_logged_in
    
    #view all chores using pagination
    def index
        @chores = Chore.order(:status).page(params[:page]).per_page(50)
    end
    
    #only shows chores assigned for the user who is currently logged in
    def show
        id = params[:id]
        @chores = Chore.find(params[:id])
        @chores = Chore.find(id)
    end
    
    #Create a new chore
    def new
        @chores = Chore.new
    end
    
    #Create chore with household id set by user who created it's household id
    #note validation on the two possible text inputs must be greater than 2,
    #less than 50
    def create 
        @chores = Chore.create(chore_params)
        if @chores.valid?
            house_id=Person.find(session[:user_id]).household_id
            @chores.update(:household_id => house_id)
            flash[:notice] = "#{@chores.task} was successfully created."
        else
            flash[:notice] = @chores.errors.full_messages[0]
        end
        redirect_to chores_path
    end

    
    #complete chore updates last_complete time to current time, and changes
    #status to green, however if it is a task (i.e. status is nil) just 
    #deletes the chore
    def complete 
        @chores = Chore.find params[:id]
        if @chores.status == nil
            @chores.destroy
            flash[:notice] = "#{@chores.task} was successfully completed."
            redirect_to chores_path
        else
            @chores.last_accomplished=Time.now
            @chores.update(:status => "green")
            flash[:notice] = "#{@chores.task} was successfully completed."
            redirect_to chores_path
        end
        
    end
    
    #update chore parameters and redirect to total chores page
    def update
       @chores = Chore.find params[:id]
       @chores.update_attributes(chore_params)
       flash[:notice] = "#{@chores.task} was successfully updated."
       redirect_to chore_path
    end
    
    #destroys a chore from the database, the only chores that are destroyed are those denoted as tasks
    def destroy
        @chores = Chore.find params[:id]
        @chores.destroy
        redirect_to chores_path
    end
    
    private 
        def chore_params
    params.require(:chore).permit(:task,:priority,:status,:description,
    :person_assigned,:last_accomplished,:history,:household,:household_id)
        end
    
end

app/views/chores/_chore_form.html.erb
<!-- Chore form for recurring chore. -->
<div class="row" style="justify-content: center;">
<%= label_tag(:Chore, nil, style: "color: white;") %>
</div>
<div class="row">
<%= text_field :chore, :task, :class => "col-md-12 choreInput" %>
</div>
<div class="row" style="justify-content: center;">
<%= label_tag(:Status, nil, style: "color: white;") %>
</div>
<div class="row">
<%= select :chore, :status, ['red', 'yellow', 'green'],{}, class: "col-md-12 dropDown choreInput" %>
</div>
<div class="row" style="justify-content: center;">
<%= label_tag(:Frequency, nil, style: "color: white;") %>
</div>
<div class="row">
<%= select :chore, :priority, ['daily', 'weekly', 'monthly'],{},class: "col-md-12 dropDown choreInput" %>
</div>
<div class="row" style="justify-content: center;">
<%= label_tag(:Person_Assigned, nil, style: "color: white;") %>
</div>
<div class="row">
<%= collection_select(:chore, :person_assigned, people_of_personal_household, :first_name, :first_name, {}, {class: "col-md-12 dropDown choreInput"}) %>
</div>

app/views/chores/_task_form.html.erb
<!-- Task form for one time task. -->
<div class="row" style="justify-content: center;">
<%= label_tag(:task, nil, style: "color: white;") %>
</div>
<div class="row">
<%= text_field :chore, :task, :class => "col-md-12 choreInput" %>
</div>
<div class="row" style="justify-content: center;">
<%= label_tag(:Finish_By, nil, style: "color: white;") %>
</div>
<div class="row">
<%= text_field :chore, :priority, :class => "col-md-12 choreInput" %>
</div>
<div class="row" style="justify-content: center;">
<%= label_tag(:Person_Assigned, nil, style: "color: white;") %>
</div>
<div class="row">
<%= collection_select(:chore, :person_assigned, people_of_personal_household, :first_name, :first_name, {}, {class: "col-md-12 dropDown choreInput"}) %>
</div>

app/views/chores/index.html.erb
<!-- Page to view household chore list -->
<div class="choreWrapper">
    <div id="page_content">
        
        <!-- Chores title-->
        <div class="text-center">
            <h1 style="color:#BDD4E7; font-size: 50px; font-weight: strong; margin-top:40px; margin-bottom:60px;";>Chores</h1>
        </div>
        
        <!-- Pop up for adding chore -->
        <div class="modal fade" id="newChoreModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
             <div class="modal-dialog" role="document">
                <div class="modal-content">
                    
                    <!--Pop up tabs task and chore-->
                    <div class="modal-header">
                        <div class="modal-title" id="ModalLabel">
                            <ul class="nav nav-tabs" id="choretable" style="width:100%;">
                                <li class="active"><a href="#chore" data-toggle="tab">New chore</a></li>
                                <li><a href="#task" data-toggle="tab">New task</a></li>
                            </ul>
                        </div>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    
                    <!--Pop up form content-->
                    <div class="modal-body">
                        <div class="tab-content">
                            
                            <!--Chore form tab-->
                            <div class="tab-pane active" id="chore" >
                                <%= form_tag chores_path, class: "newChore", :method => :post do |f|%>
                                    <%= render(:partial => 'chore_form', :locals => {:f => f}) %>
                                    <div class="row" style="justify-content: center;">
                                    <%= button_tag(type: "submit",  class: "btnSubmit btn btn-sm") do %>
                                        <span class="glyphicon glyphicon-plus"></span></div>
                                    <% end %>
                                <% end %> 
                            </div>
                            
                            <!--Task form tab-->
                            <div class="tab-pane" id="task" >
                                <%= form_tag chores_path, class: "newChore", :method => :post do |f|%>
                                    <%= render(:partial => 'task_form', :locals => {:f => f}) %>
                                    <div class="row" style="justify-content: center;">
                                    <%= button_tag(type: "submit",  class: "btnSubmit btn btn-sm", style:"justify-content:center;") do %>
                                        <span class="glyphicon glyphicon-plus"></span></div>
                                    <% end %>
                                <% end %> 
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>    
    
        <!--navigation tab options, all chores and needs to be done-->
        <ul class="nav nav-tabs" id="choretable" style="width:100%;">
            <li class="active"><a href="#all" data-toggle="tab">All chores</a></li>
            <li><a href="#uncompleted" data-toggle="tab">Needs to be done </a></li>
            <div class="col-md-8"></div>
            <button type="button" class="btn" style="background:none;" data-toggle="modal" data-target="#newChoreModal">
              <span class="glyphicon glyphicon-plus"></span>
            </button>
        </ul>
        
        <div class="tab-content">
            
            <!--Chore list for all chores tab-->
            <div class="tab-pane active" id="all" >
                <div class="choreWrapper">  
                <%ses_id=session[:user_id]
                ses_house_id=Person.find(ses_id).household_id
                if ses_house_id!=nil%>   
                    <div id="tableWrapper">
                        <br>
                        <div class="row">
                            <div id="tableScroll">
                                <table class="table table-hover table-fixed">
                                    <thead>
                                        <tr>
                                            <th id="choreHeader">Task</th>
                                            <th id="choreHeader">Current Status</th>
                                            <th id="choreHeader">Frequency</th>
                                            <th id="choreHeader">Person Assigned</th>
                                            <th id="choreHeader">Complete</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <%if @chores
                                            @chores.each do |t| 
                                                if t.household_id==ses_house_id%>
                                                    <tr>
                                                        <td><a href="<%= chores_path %>/<%= t.id %>"><%= t.task %> </a> </td>
                                                        <td><span class="circle", style = <%="color:#{chores_logic(t)}"%>></span></td>
                                                        <td><%= t.priority %></td>
                                                        <td><%= t.person_assigned%></td>
                                                        <td><%= link_to "Complete", complete_chores_path(:id => t.id), :class => "button", :method => "GET" %></td>
                                                    </tr>
                                               <%end%>
                                            <%end%> 
                                        <%end%>
                                        <%= will_paginate @chores, previous_label: h("<"), next_label: h(">") %>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                <%else%>
                    <h2><%= link_to "Please join or create a household first", households_path %></h2>
                <%end%>
                </div>
            </div>
    
            <!--Chore list for needs to be done chores tab-->
            <div class="tab-pane" id="uncompleted">
                <div class="choreWrapper">  
                <%ses_id=session[:user_id]
                ses_house_id=Person.find(ses_id).household_id
                if ses_house_id!=nil%>   
                    <div id="tableWrapper">
                        <br>
                        <div class="row">
                            <div id="tableScroll">
                                <table class="table table-hover table-fixed">
                                    <thead>
                                        <tr>
                                            <th id="choreHeader">Task</th>
                                            <th id="choreHeader">Current Status</th>
                                            <th id="choreHeader">Frequency</th>
                                            <th id="choreHeader">Person Assigned</th>
                                            <th id="choreHeader">Complete</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <%if @chores 
                                            @chores.each do |t| 
                                                if (t.household_id==ses_house_id) && (chores_logic(t) == "red" || chores_logic(t) == "purple") %>
                                                    <tr>
                                                        <td><a href="<%= chores_path %>/<%= t.id %>"><%= t.task %> </a> </td>
                                                        <td><span class="circle", style = <%="color:#{chores_logic(t)}"%>></span></td>
                                                        <td><%= t.priority %>   </td>
                                                        <td><%= t.person_assigned%></td>
                                                        <td><%= link_to "Complete", complete_chores_path(:id => t.id), :class => "button", :method => "GET" %></td>
                                                    </tr>
                                                <%end%>
                                            <%end%> 
                                        <%end%>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                <%else%>
                   <h2><%= link_to "Please join or create a household first", households_path %></h2>
                <%end%>
                </div>
            </div>
        </div>
    </div>  
</div>

<script>
    $(document).ready(function() {
        $('choretable a:first').tab('show');
    })
</script>

app/views/chores/show.html.erb
<!--Show chore information page and update chore form-->
<div id = "choreProf">
<div id="page_content">

<!--Main chore info card-->
<div class="row">
    
    <!--Insert Broom image-->
    <div class="card" style="width: 350px; background: #DEFFED;">
        <img class="card-img-top" src="/assets/chore.jpg" alt="Card image cap"/>
    </div>
    
    <!--Chore content display-->
    <div class="card" style="width: 620px;">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <h1 style="text-align:center; color:black; padding-top: 15%; padding-bottom: 15%; font-size: 32px;"> Details about <%= @chores.task %> </h1>
            </div>
        </div>
        
        <!--Chore content headers-->
        <div class="row">
            <div class="col-md-4" style="text-align:center;">
                <p>Last completed:</p>
            </div>
            <div class="col-md-4" style="text-align:center;">
                <p>Status:</p>
            </div>
            <div class="col-md-4" style="text-align:center;">
                <p>Frequency:</p>
            </div>
        </div>
        
        <!--Chore header values-->
        <div class="row">
            <div class="col-md-4" style="text-align:center;">
                <p style="font-size: 22px;">
                    <!--display time in central time-->
                    <% if @chores.last_accomplished != nil%>
                        <%= Time.at(@chores.last_accomplished).in_time_zone("Central Time (US & Canada)").strftime("%B %e, %Y at %I:%M %p")  %>
                    <%else%>
                        <%=Time.at(@chores.created_at).in_time_zone("Central Time (US & Canada)").strftime("%B %e, %Y at %I:%M %p")%>
                    <%end%>
                </p>
            </div>
            <div class="col-md-4" style="text-align:center;">
                <p style="font-size: 22px;"><span class="bigcircle", style = <%="color:#{chores_logic(@chores)}; font-size:60px!important;"%>></span></p>
            </div>
            <div class="col-md-4" style="text-align:center; padding-right: 15px;">
                <p style="font-size: 22px;"><%= @chores.priority%></p>
            </div>
        </div>
        <div class = "row">
            <div class="col md-6 offset-md-3">
                <p style="font-size: 22px;">Person assigned: <%= @chores.person_assigned %></p>
            </div>
        </div>
    </div>
</div>

</br>

<!--Update chore form-->
<div class="row">
    <div class="card col-md-6 offset-md-3">
        <h2 style="color:black;">Update Chore</h2>
        <div id="updateperson">
            <%= form_tag chore_path, :method => :put do %>
            <%= label :chore, :task, 'Chore' %>
            <%= text_field :chore, :task  %>
            </br>
            <%= label :chore, :status, 'Status' %>
            <%= select :chore, :status, ['red', 'yellow', 'green'],{},class: "col-md-12 dropDown choreInput" %>
            </br>
            <%= label :chore, :priority, 'Priority' %>
            <%= select :chore, :priority, ['daily', 'weekly', 'monthly'],{},class: "col-md-12 dropDown choreInput" %>
            </br>
            <%= label :chore, :person_assigned, 'Person assigned' %>
            <%= collection_select(:chore, :person_assigned, people_of_personal_household, :first_name, :first_name, {}, {class: "col-md-12 dropDown choreInput"}) %>
            </br>
            <%= submit_tag 'Update'%>
            <% end %>
        </div>
    </div>
</div>

</br>
</br>

<!--Link back to previous page -->
<div id="linkback">
<%= link_to 'Back to chore list', chores_path %>
</div>
</div>
</div>