config/routes.rb
  Rails.application.routes.draw do

  get 'access/login'
  get 'access/attempt_login'
  post 'access/attempt_login'
  get 'access/logout'
  get 'people/signup' 
  get 'access/landing'
  get 'access/home'
  
    resources :chores do
      collection do
        get 'complete'
      end
    end
    resources :people do
      collection do
        get 'joinhouse'
      end
    end
    resources :households do
      collection do
        get 'join'
      end
    end
        
    root :to => redirect('/access/landing')
    
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/') 
    
  end

 

app/models/household.rb
class Household < ActiveRecord::Base
    #household model with has many people and chores, validates name presence and length
    has_many :people
    has_many :chores

    validates :name, :presence => true,
                    :length => { :within => 2..50 }
    validates_uniqueness_of :name, :message => "House name already taken"
end

app/controllers/households_controller.rb
class HouseholdsController < ApplicationController
    
    #controller for household to connect users together and assign chores to only
    #those in the household
    before_action :confirm_logged_in, :except => [:joinHousehold]
    def index
        @households = Household.order(:name).page(params[:page]).per_page(5)
    end
    
    def show
        id = params[:id]
        @households = Household.find(params[:id])
        @households = Household.find(id)
    end
    
    def new
        @households = Household.new
    end
    
    #Create household with validation on the text input to be greater than 2,
    #less than 50
    def create 
        @households = Household.create(household_params)
        if @households.valid?
            flash[:notice] = "#{@households.name} was successfully created."
        else
            flash[:notice] = @households.errors.full_messages[0]
        end
        redirect_to households_path
    end
    
    def update
        @households = Household.find params[:id]
        @households.update_attributes(household_params)
        flash[:notice] = "#{@households.name} was successfully updated."
        redirect_to household_path(@households)
    end
    
    def destroy
        @households = Household.find params[:id]
        @households.destroy
        redirect_to households_path
    end
    private 
        def household_params
    params.require(:households).permit(:name,:people,:chores)
        end
    
end

app/helpers/households_helper.rb
module HouseholdsHelper
end

app/views/households/index.html.erb
<!--List all households and choose to create and or join one-->
<div id="page_content">
    
    <!--Header with google map-->
    <div class="text-center">
        <div id="profiletop">
            <h1>Households</h1>
        </div>
        <div id="map"></div>
    </div>
    
    <!--Households table with join house options-->
    <table style="width:100%">
        <!--Table headers-->
        <tr>
            <div class="tbl-header">
                <th>Households</th>
                <th>Members of Household</th>
                <th>Join Household</th>
            </div>
        </tr>
        <%if @households
            @households.each do |t| %>
                <tr>
                    <td><a href="<%= households_path %>/<%= t.id %>"><%= t.name %> </a> </td>
                    <td><% people = people_of_any_household(t) %> 
                        <% people.each do |p| %> <%= p.first_name%> <%= p.last_name%>,
                        <% end %></td>
                    <td><%= link_to "Join", joinhouse_people_path(:id => t.id), :class => "button", :method => "GET" %></td>
                </tr>
            <%end%> 
        <%end%>
    </table>
    
    <!--Create household form-->
    <br>
    <%= will_paginate @households, previous_label: h("<"), next_label: h(">") %>
    <h2>Add Household</h2>
    <%= form_tag households_path, class: "newHousehold", :method => :post do %>
        <%= label :households, :name, 'Name:', style: "color: white;" %>
        <%= text_field :households, :name %>
        <%= submit_tag 'Submit'%>
    <% end %>

</div>

<!--google maps script-->
<script>
    function initMap() {
        var uluru = {lat: 29.940994, lng: -90.118619};
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 16,
          center: uluru
        });
        var marker = new google.maps.Marker({
          position: uluru,
          map: map
        });
    }
</script>
<script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAacBm75-nBRb0-g8tqEFKyjmmUuggC6G8&callback=initMap">
</script>
    

app/views/households/show.html.erb
<!--Display individual house information-->
<div id="page_content">
    <div class="row">
        <div class="card col-md-10 offset-md-1">
            
            <!--House details header-->
            <div class="row">
                <div class="col-md-6 offset-md-3">
                    <h1 style="text-align:center; color:black; padding-top: 15%; padding-bottom: 15%; font-size: 32px;"> House details </h1>
                </div>
            </div>
            
            <!--House content headers-->
            <div class="row">
                <div class="col-md-4" style="text-align:center;">
                    <p>House name</p>
                </div>
                <div class="col-md-4" style="text-align:center;">
                    <p>House members</p>
                </div>
            </div>
            
            <!--House content information-->
            <div class="row">
                <div class="col-md-4" style="text-align:center;">
                    <p style="font-size: 22px;"><%= @households.name %></p>
                </div>
                <div class="col-md-4" style="text-align:center;">
                    <p style="font-size: 22px;"><% people = people_of_any_household(@households) %> 
                        <% people.each do |p| %>
                            <li><%= p.first_name%> <%= p.last_name%></li>
                        <% end %>
                    </p>
                </div>
            </div>
        </div>
    </div>
    
    <!--Link back to household list-->
    <div id="linkback">
        <%= link_to 'Back to house list', households_path %>
    </div>
</div>